name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  B2_ID: ${{ secrets.B2_ID }}
  B2_KEY: ${{ secrets.B2_KEY }}
  IMAGE_NAME: duplicacy-autobackup # local

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build local Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

      - name: Install Duplicacy
        run: |
          sudo wget https://github.com/gilbertchen/duplicacy/releases/download/v3.1.0/duplicacy_linux_x64_3.1.0 -O /usr/bin/duplicacy
          sudo chmod +x /usr/bin/duplicacy

      - name: Run integration tests
        run: |
          bash tests/test-immediate-backup.sh
          bash tests/test-pre-post-scripts.sh
